language: java
jdk:
- openjdk8
dist: trusty

env:
  matrix:
  - VERSION=1.0.1

install: mvn install

script: 
  - docker build -t drivereu/icon-service:latest -t drivereu/icon-service:$VERSION .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push drivereu/icon-service

cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
